### ISSUE TITLE
Issue support

### ISSUE THREAD

**Issue by jlczuk** [WASdev/sample.zos.provision.was#2]
If customers have problems running this template, can they reasonable expect responses to issue they might open here?  Or should they adhere to the standard service process via RETAIN PMRs?

**Comment by kaczyns** [comment]
@jlczuk Hi John - the templates are supported here via Github issues.  Our developers monitor this Github repository.  The templates are provided as samples and not as product code, but we will make reasonable efforts to help customers get them working on their system.

**Comment by jlczuk** [comment]
Thanks Tim.  That's perfect as far as I'm concerned.
